#+TITLE: "De plazas de mercado y yerbateras"

* Sinpsis
Relato sobre yebatera que rememora sus inicios como frutera y su transformacion en Yerbatera, a lo largo
del proceso de modernización de Bogotá.

* Plaza Samper Mendoza
- atados (de precio estimado)
- chaquetas estampadas
- local fijo
- paga arriendo al estado
- otros tienen puestos itinerantes
- aseo de su puesto para bajar costos de operación
- se remonta a décadas antes de la Samper Mendoza
- muchos mayristas compran atados para distribuir a otras ciudades
** Gestión EDIS
- 1958
- ordeno el espacio del mercado
- asigna locales y espacios a cada vendedor
- inicia arrendamiento
- 
* tradición
- ruanas de lana de chivo 

* Paloquemao
- cuidad y limpiar productos para conservarlos
- conocer ciclos de la fruta
- restricciones la obligaron a moverse a calle 19 (DAS), luego a la carrillera del tranvía
- por último llega a la Samper Mendoza, cuando había poca concurrencia de vendedores de yerbas
- vivió plantación de una bomba al DAS

* Aprender el oficio de yerbas
- nunca las cultivaron
- compañeros venían de pueblos y les enseñaron. Chipaque
- circuito de intercambio de conocimiento de sus propiedades en las plazas
- Plaza España. San Victorino, mercados itinerantes
- reune calentanas, sabaneras, 

* S. XX 
- se evidencia relación estrecha con las yerbas 
- persiste a pesar de intentos de modernización
* EDIS
- plazas públicas quieren relegarse a ornato
- lugares de abasto en espacios cerrados
- impulsado por el proceso de odernización

* Usos esotéricos
- El mercado vende más este tipo de yerbas cuando se acerca diciembre y los capitalinos quieren acudir a las plantas para garantizar un año nuevo próspero y exitoso.

* Usos gastronómicos

#+BEGIN_QUOTE
"...llegaban muchos a comprar estas hierbas en la madrugada para preparar las famosas aromáticas y canelazos, bebidas altamente apreciadas por los bogotanos en las horas más frías del día. Sin embargo, cuentan en la plaza que las restricciones de uso del espacio público han hecho que muchos hayan dejado esta actividad. También es común la compra de yerbas que puedan ser usadas en la preparación de carnes como el laurel y el tomillo."
#+END_QUOTE

