#+Author: Jonatan Ahumada Fernández
#+Title: Anteproyecto

| Título | /Iglesias: El espíritu colonial en la metrópolis bogotana/ |


** Introducción 
El continente Americano está aún marcado por lagg Conquista. Por ese motivo,
la discusión sobre su identidad, su historia y sus ráices --si se quiere, su espíritu-- ha sido 
fuente de grandes disputas. La figura de la Iglesia, con toda su carga simbólica ha tenido un 
protagonismo perenne en el transcurso del desarrollo de la Nación, como se puede evidenciar 
desde la fundación "mítica" de Santa Fé. No obstante, las iglesias no son solo una reliquía del 
pasado, o un símbolo bochornoso de una conquista violenta. En torno a ellas, se ha formado 
toda una mística, un imaginario, que aún hoy persiste como un componente fundacional de lo que es 
Bogotá. Basta ir a la Plaza de Bolivar y ver la Catedral o el monumento a los próceres del Colegio
San Bartolomé para intuir la potencia que inspiran esas curiosas construcciones. Pero la extensión 
todal del símbolo de la iglesia es aún más basta, es a un tiempo popular y culta. Bajo el auspicio 
de Nuestra Señora de Lourdes puedes comprar marihuana sin que los policías del CAI te molesten o 
puedes también viajar al medioevo en la oscuridad de Nuestra Señora del Carmen. En medio de 
del ansia por modernizar a Bogotá, esas construcciones líticas siguen anclando la ciudad a su 
pasado de tierra de nadie. 

 
** Objetivo General
El objetivo general del trabajo es entablar un diálogo, en la medida de lo posible, entre la academia y lo popular en
torno a la figura de la iglesia. Por un lado, hay todo un discurso acerca del significado de la arquitectura colonial
en el marco de la Conquista. Según este este enfoque, guardando los matices, las iglesias son instrumentos 
de evangelización que modifican por completo la cosmovisión precolonial de nuestros antepasados indígenas. Por otro lado,
desde una perspectiva casual, vivencial, estas son recintos donde el citadino corriente desahoga sus pesares a la hora del almuerzo,
en donde los enboladores cazan clientes y al frente de las cuales se hacen mercados de pulgas. Este extraño encuentro entre 
dos mundos es la chispa que alentará el trabajo por cuanto que parece ser una metáfora que encapsula muy bien las contradicciones,
así como la historia de la ciudad de Bogotá.

** Objetivos específicos 
*** Revisión biblográfica
 El objetivo de esta revisión no es leer la bibliografía como un historiador o un arquitecto.
 No se recopilará un acervo de datos o descripciones técnicas. Sino que se tratará de buscar un "espíritu",
 que encapsule los imaginarios sobre la temática. El objetivo final será poner citas de las fuentas bibliográficas al lado de las fotos. Estás, por sí mismas, contarán una historia. 
*** Excursión fotográfica
El objetivo es juntar el material suficiente para hacer una exposición fotográfica. Las condiciones son las mismas que las del punto anterior: la idea es capturar fotos que revelen imaginarios ya sean "urbanos"(por ejemplo, un lisiado a la entrada), sino también coloniales (ornamentación barroca, etc).

*** Conformación de la exposición
El aspecto material del proyecto se hará al final. Se intentará hacer una página web que sirva como exposición (lineamientos abajo),
 pero en caso de encontrar dificultades técnicas se armará un libro que emule los "Libros de Gran Formato", el género antonomásico de la bibliografía escogida.




** Metodología

*** Características de la exposición 
La exposición seguirá el ejemplo de los libros del Banco Cafetero de Colombia. Estos fueron los libros que más aparecieron en la revisión bibliográfica. 
Llaman la atención porque son muy antiguos (marcan su año de publicación en latín, por ejemplo), y aún hoy diversas empresas publican esos libros 
que hacen de propaganda al patrimonio cultural del país. La estructura básica es:

- Una introducción a la naturaleza de la exposición
- las fotos acompañadas con una descripción.

En mi caso, la descripción, como tratará de entablar un diálogo, consistirá en:

- una cita del material bibliográfico (perspectiva académica)
- una cita tomada de una pregunta a un transeunte (perspectiva urbana)

*** Las preguntas
En las excursiones fotográficas me he dado cuenta que los lugares más fructiferos son:

| Iglesia de San Francisco             | mendigos, septimazo, skaters                                          |
| Iglesia de Lourdes                   | wventos de todo tipo, expendedores de droga, trabajadores en descanso |
| Iglesia de Las Nieves                | mercado de pulgas, septimazo                                          |
| Iglesia La Porciúncula               | emboladores, estatua robada, zona ejecutiva                           |
| Iglesia de Nuestra Señora del Carmen | turistas, colegios, universidades                                     | 

Las preguntas serán:
- ¿Por qué vienes aquí?
- ¿Qué significa la iglesia para tí?
- ¿Crees que es algo "autóctono"?  

** Modo de entrega
El modo de entrega escogido es la página web. Es un medio con el que soy algo familiar y me permite entroncar 
con mi carrera. La ventaja de la página web es que es portable y fácil de referenciar. La desventaja 
es que el formato de exposición fotográfica tendrá que adaptarse a este medio, pero eso será lo interesante.




                                  





