#+TITLE: Trabajo en bases de datos I
#+AUTHOR: Jonatan Ahumada Fernández

* La idea principal del artículo en términos de que problema está tratando de resolver
El objetivo del artículo es presentar una nueva estructura de datos en forma de árbol llamada EERTREE. La utilidad
de esta nueva estructura radica en que simplifica y acelera las operaciones relacionadas con palíndromos
en las cadenas de caracteres (/strings/). Entre las operaciones con palíndromos se encuentran: 1) búsqueda, 2) conteo, 3) listado 
y 4) factorización de una cadena en sus palíndromos. 

Estructuralmente, cada nodo del dígrafo de esta nueva estructura del EERTREE corresponde 
a un factor palindrómico de la cadena que representa. Esto da a entender que es una estructura altamente especializada en resolver  este tipo 
de problemas algoritmicos. El artículo presenta como /benchmark/ que el "mantenimiento" de un EERTREE para una cadena de longitud \(n\)
con \sigma símbolos distintos es de tiempo  \(O(n log \sigma)\)y de espacio \(O(n log \sigma)\.



* La relación del artículo con estructuras de datos.
Según el artículo, los palíndromos son una de las estructuras más recurrentes dentro de las cadenas de caracteres. 
Esto ya de por sí enmarca el tema dentro del objetivo general de las estructuras de datos mencionado en la
apertura del presente curso: "el mundo está desordenado, las estructuras de datos permiten ordenarlo".

Además, el estudio de los palíndromos es un tema de bastante interés
en área de las combinatorias, la teoría de los lenguajes formales y la /stringology/. Por lo tanto, 
vemos que podría tener diversas aplicaciones. La aplicación más importante mencionada en el artículo, a mi parecer,
fue el estudio del RNA (ácido ribonucleico).  

* La contribución del uso de temas de estructuras de datos en el artículo.
El artículo tiene muchos puntos de encuentro con los temas del plan analítico del curso. Para empezar por lo obvio, se 
trata de una estructura de datos. Además, el EERTREE es un árbol, estructura que abordamos para resolver los problemas de 
combinatorias. Implícitamente, el artículo describe el EERTREE como un ADT (el /paper/ es de hecho una especificación para el ADT), pues describe esta estructura en términos matemáticos y 
además especifíca qué operaciones debe tener su implementación y cómo deberían funcionar. Por último, las mediciones de la eficiencia 
del EERTREE se hacen con notacón \Big O\.


